ANSIBLE_HOME=~/.ansible
export ANSIBLE_HOME

ANSIBLE_CONFIG=./ansible.cfg
export ANSIBLE_CONFIG

KUBE_CONFIG=~/.kube/config
export KUBE_CONFIG

# For ansible
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY
